---
title: "Case Study: Implementing a Diversity Ecosystem in City Purchasing "
author: "Stephanie Gutierrez"
date: 'February 4, 2026'
format: 
  html: 
    toc: true
    toc-depth: 4
    number-sections: true
    code-link: true
    embed-resources: true
editor: visual
execute: 
  freeze: auto
---

# Exploratory Research (Chapter 4)

## Response 1.

::: panel-tabset
What qualitative method would you use in a government setting regarding diversity issues?
:::

My recommended qualitative method to learn how employees feel about supplier diversity would be a focus group. The focus group should consist of employees from different departments and different longevity within their department.  Doing this could help the marketing team explore different concerns each department can have and gain insight from employees who are new and have been at the company for many years. A group setting can help reveal misunderstandings and views about things not discussed in surveys.

::: callout-note
**Questions:**

1\. “Describe a time the city's new initiative felt fair or unfair, and why?”

2\. “What does changing the supplier diversity mean to you?”

3\. “What would you want city leaders to explain more clearly about this initiative?”
:::

# **Descriptive / Predictive Research (Chapter 5)**

## Response 2.

A survey design for the employees consists of creating questions for employees that can be distributed electronically for those who work remotely, and get more people to answer. Selecting a stratified random sample to make sure the answers are random, anonymous, and fairly diverse. The starta could include different departments, job roles, and tenure years. Creating this sample will help make it easier to compare how each group feels about the supplier diversity initiative. 

::: callout-note
**Questions:**

Using Likert Scale-

-   Strongly Disagree

-   Disagree

-   Neutral

-   Agree

-   Strongly Agree

1.  “I feel informed by sharing my concerns regarding new city initiatives.”
2.  “Changing the supplier diversity is necessary for the city to serve our community.”
3.  “I trust the city to make supplier decisions that are transparent and fair.”
:::

# **Secondary Research & Benchmarking**

> *What is one source of secondary data that can guide the city initiative.*

## Response 3.

One source of secondary data that could guide the city initiatives could be data collected from prior annual reports and prior case studies. Statistics in the reports can have data from similar past initiatives and employee attitudes during that time. Reviewing the data can help you create new survey questions about fairness and city initiative transparency.  Recognizing patterns can help answer questions that you may have now with the data collected previously. 

End of Document.[^1]

[^1]: This is the footnote text.
